### ISSUE TITLE
Unexpected ValueError

### ISSUE THREAD

**Issue by magrenimish** [facebookresearch/frankmocap#109]
Hi
I was successfully able to run the demo on google colab a few weeks ago but now when I try to run it, I am getting the following error:
**Loading Body Pose Estimator
Loading Third View Hand Detector
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/frankmocap/demo/demo_handmocap.py", line 179, in <module>
    main()
  File "/content/frankmocap/demo/demo_handmocap.py", line 165, in main
    hand_mocap = HandMocap(args.checkpoint_hand, args.smpl_dir, device = device)
  File "/content/frankmocap/handmocap/hand_mocap_api.py", line 44, in __init__
    self.model_regressor = H3DWModel(self.opt)
  File "/content/frankmocap/handmocap/hand_modules/h3dw_model.py", line 126, in __init__
    ext='pkl').cuda()
  File "/usr/local/lib/python3.7/dist-packages/smplx/body_models.py", line 2389, in create
    return SMPLX(model_path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/smplx/body_models.py", line 960, in __init__
    model_data = pickle.load(smplx_file, encoding='latin1')
ValueError: invalid \x escape at position 55942**

Any idea on how I could fix this issue?
Thanks

**Comment by penincillin** [comment]
The error seems to be caused by reading SMPL-X data file. Would you mind check whether the downloaded SMPL-X data file is complete ?

**Comment by magrenimish** [comment]
Hi 
Yes, re-uploading the pth model file helped solve the issue.
Cheers
