### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by cloudweather** [facebookresearch/frankmocap#13]
Hi,
I've encountered this error when running:
```
python -m demo.demo_handmocap --input_path ./sample_data/han_hand_short.mp4 --out_dir ./mocap_output
```

I am running on Windows 10 Conda. I think I've successfully built detectron2 but not sure if this is its problem or something else.

```
Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\venv_frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\anaconda3\envs\venv_frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\frankmocap\frankmocap\demo\demo_handmocap.py", line 16, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "G:\frankmocap\frankmocap\handmocap\hand_bbox_detector.py", line 30, in <module>
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named 'model'
```

How can I solve this? Thank you.

**Comment by SasuraiNoHoge** [comment]
I have encountered the same issue.I want to know the execution environment that works.
Incidentally body motion capture work in my environment.

# Execution Environment
| OS            | Ubuntu 18.04 LTS |
| :------------ | :--------------- |
| CUDA          | 10.1             |
| nvidia driver | 450.66           |
| memory        | 32GB             |
| GPU           | GeForce GTX 1080 |


# Error
```bash
Traceback (most recent call last):
  File "/home/sasurainohoge/.pyenv/versions/anaconda3-2020.07/envs/venv_frankmocap/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sasurainohoge/.pyenv/versions/anaconda3-2020.07/envs/venv_frankmocap/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sasurainohoge/workspace/frankmocap/demo/demo_handmocap.py", line 16, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/home/sasurainohoge/workspace/frankmocap/handmocap/hand_bbox_detector.py", line 30, in <module>
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named 'model'

```

I've encountered FAILED in Installation when running:

```bash
sh scripts/install_frankmocap.sh
```

<details><summary>long output</summary>

```bash
...
creating /home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/build/temp.linux-x86_64-3.7/home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc/cuda
Emitting ninja build file /home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/6] /usr/local/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc -I/home/sasurainohoge/Env/frankmocap/lib/python3.7/site-packages/torch/include -I/home/sasurainohoge/Env/frankmocap/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/sasurainohoge/Env/frankmocap/lib/python3.7/site-packages/torch/include/TH -I/home/sasurainohoge/Env/frankmocap/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/sasurainohoge/.pyenv/versions/anaconda3-2020.07/envs/venv_frankmocap/include/python3.7m -c -c /home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc/cuda/ROIPool_cuda.cu -o /home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/build/temp.linux-x86_64-3.7/home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc/cuda/ROIPool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/build/temp.linux-x86_64-3.7/home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc/cuda/ROIPool_cuda.o 
/usr/local/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc -I/home/sasurainohoge/Env/frankmocap/lib/python3.7/site-packages/torch/include -I/home/sasurainohoge/Env/frankmocap/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/sasurainohoge/Env/frankmocap/lib/python3.7/site-packages/torch/include/TH -I/home/sasurainohoge/Env/frankmocap/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/sasurainohoge/.pyenv/versions/anaconda3-2020.07/envs/venv_frankmocap/include/python3.7m -c -c /home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc/cuda/ROIPool_cuda.cu -o /home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/build/temp.linux-x86_64-3.7/home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc/cuda/ROIPool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc/cuda/ROIPool_cuda.cu: In function ‘std::tuple<at::Tensor, at::Tensor> ROIPool_forward_cuda(const at::Tensor&, const at::Tensor&, float, int, int)’:
/home/sasurainohoge/workspace/test/frankmocap/detectors/hand_object_detector/lib/model/csrc/cuda/ROIPool_cuda.cu:115:62: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   AT_ASSERTM(input.type().is_cuda(), "input must be a CUDA tensor");
...
```
</details>

**Comment by jhugestar** [comment]
Hi all, 

It seems like both issues came from detectron2 installation which is used to detect hand bbox (we use [100DOH](https://fouheylab.eecs.umich.edu/~dandans/projects/100DOH/download.html)). FYI, Body module has no dependency on the detectron2. 

A good way to debug this is to try to run 100DOH source code separately (using its own example demo code) and see whether you have the similar issues or now.

**Comment by spobwoode** [comment]
Same issue here. Has anybody got this working? Thanks.

**Comment by jhugestar** [comment]
@SasuraiNoHoge 

"model.utils.config import cfg as cfgg": 

This is a part in 100DOH: https://github.com/ddshan/hand_object_detector/blob/master/lib/model/utils/config.py

It seems like this has not been installed correctly, since you got failures in installing detectron2. 

As explained in our [readme](https://github.com/facebookresearch/frankmocap/blob/master/docs/INSTALL.md), the proper installation order is 

detectron2 -> 100DOH

Can you elaborate more about how you installed detectron2?

For example, the following is a way I installed detectron2:

 python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.6/index.html

**Comment by ddshan** [comment]
Thanks for the great work and code release.

I had similar errors when compiling the hand object detector.
My short-term solution, which works for me is to install pytorch1.4 instead of pytorch1.6
`conda install -c pytorch pytorch==1.4.0 torchvision cudatoolkit=10.1`

**Comment by penincillin** [comment]
@ddshan 
Thanks for sharing you solution here :)
Also, thanks for sharing you brilliant code of hand detection :)

**Comment by SasuraiNoHoge** [comment]
@jhugestar, @ddshan 
Thank you.
I solved my problem.
## Changed My Environment

|    |    |
| ---- | ---- |
|  OS  |  Ubuntu 18.04 LTS  |
|  CUDA  |  10.1  |
| nvidia driver | **435.21** |
| GPU | GeForce GTX 1080 |
| torch | **1.4.0** |
| torchvision | **0.5.0** |

Cause of my error was:
- CUDA and nvidia driver versions are compatible.
- torch 1.6.0 is not supported nvidia driver 435.21
- not to install g++.

Solved with this commnad.
```bash
sudo apt-get install g++-5
pip install torch==1.4.0 torchvision==0.5.0
conda install torch=1.4.0 torchvision=0.5.0
```

**Comment by penincillin** [comment]
@SasuraiNoHoge 
That's great ! 
Thanks for sharing your solution here !

**Comment by lircstar** [comment]
@SasuraiNoHoge I still make the same error in your way. 

  from handmocap.hand_bbox_detector import HandBboxDetector
  File "/home/yucheng/frankmocap/frankmocap/handmocap/hand_bbox_detector.py", line 30, in <module>
    from model.utils.config import cfg as cfgg
ModuleNotFoundError: No module named 'model'

**Comment by penincillin** [comment]
@lircstar 
This bug is related to detectron2. Can you try to install detectron2 only ? And see if there are any errors.

**Comment by Faizan-Saifullah** [comment]
Mine works after :

sh scripts/install_frankmocap.sh
