### ISSUE TITLE
AssertionError: Failed in opening video

### ISSUE THREAD

**Issue by CGMikeG** [facebookresearch/frankmocap#157]
I get an error after running below command. Detectron2 and sample data have been installed successfully. 

python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output

Traceback (most recent call last):
  File "C:\Anaconda\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "M:\GITHUB\FRANKMOCAP\demo\demo_bodymocap.py", line 178, in <module>
    main()
  File "M:\GITHUB\FRANKMOCAP\demo\demo_bodymocap.py", line 174, in main
    run_body_mocap(args, body_bbox_detector, body_mocap, visualizer)
  File "M:\GITHUB\FRANKMOCAP\demo\demo_bodymocap.py", line 27, in run_body_mocap
    input_type, input_data = demo_utils.setup_input(args)
  File "M:\GITHUB\FRANKMOCAP\mocap_utils\demo_utils.py", line 105, in setup_input
    assert cap.isOpened(), f"Failed in opening video: {args.input_path}"
AssertionError: Failed in opening video: ./sample_data/han_short.mp4

**Comment by penincillin** [comment]
@CGMikeG 
Would you mind check whether ```./sample_data/han_short.mp4``` is in the correct path?
