### ISSUE TITLE
ModuleNotFoundError: No module named 'demo'

### ISSUE THREAD

**Issue by CGMikeG** [facebookresearch/frankmocap#158]
I am currently trying to test frankmocap in Linux Mint hoping I can make it work. I think I have installed all the dependencies propely. Unfortunately I am getting below error.

python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
/home/lalala/Downloads/yes/envs/frankmocap/bin/python: Error while finding module specification for 'demo.demo_bodymocap' (ModuleNotFoundError: No module named 'demo')

**Comment by penincillin** [comment]
@CGMikeG 
Would you try to install the detectron-2 according to their [official guidance](https://detectron2.readthedocs.io/en/latest/tutorials/install.html)? Please make sure you choose the right installation package matching your operating system, CUDA-version, and GPU version

**Comment by CGMikeG** [comment]
I didn't get any error when I use detectron2 install script from this frankmocap. But I can see now that they recommend using torch 1.7 and 1.8 for cuda 10.1. I will start with that if it fails I will see if running their script will do the trick. :D

**Comment by CGMikeG** [comment]
I have updated pytorch using below command

conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.1 -c pytorch


And installed reinstalled detectron2 using below ,

python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

Unfortunately, after runnning below I am still getting the same error.

python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output

Traceback (most recent call last):
  File "/home/lalala/Downloads/yes/envs/frankmocap/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lalala/Downloads/yes/envs/frankmocap/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lalala/frankmocap/demo/demo_bodymocap.py", line 16, in <module>
    from demo_options import DemoOptions
ModuleNotFoundError: No module named 'demo_options'

**Comment by CGMikeG** [comment]
For anyone who would have the same issue. You can try to resolve
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
