### ISSUE TITLE
Run demo returns error

### ISSUE THREAD

**Issue by MolianWH** [facebookresearch/frankmocap#16]
# Envs
Cuda: 10.1
Cudnn: 7.6.0
pytroch: 1.6.0

# Details
I run this
```shell
python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
```
and return TypeError
```shell
Traceback (most recent call last):
  File "/home/dreamdeck/anaconda3/envs/venv_frankmocap/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dreamdeck/anaconda3/envs/venv_frankmocap/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dreamdeck/Documents/code/3DReconstruction/frankmocap/demo/demo_frankmocap.py", line 246, in <module>
    main()
  File "/home/dreamdeck/Documents/code/3DReconstruction/frankmocap/demo/demo_frankmocap.py", line 242, in main
    run_frank_mocap(args, hand_bbox_detector, body_mocap, hand_mocap, visualizer)
  File "/home/dreamdeck/Documents/code/3DReconstruction/frankmocap/demo/demo_frankmocap.py", line 178, in run_frank_mocap
    body_mocap, hand_mocap)
  File "/home/dreamdeck/Documents/code/3DReconstruction/frankmocap/demo/demo_frankmocap.py", line 104, in run_regress
    pred_body_list, pred_hand_list, body_mocap.smpl, img_original_bgr.shape)
  File "/home/dreamdeck/Documents/code/3DReconstruction/frankmocap/intergraion/copy_and_paste.py", line 209, in intergration_copy_paste
    integral_output['pred_left_hand_betas'] = hand_info['left_hand']['pred_hand_betas']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by MolianWH** [comment]
Thanks. I tried ` pip install -U torch==1.6` , and it works. 
But there is another error
```shell
 from model import _C
ImportError: /home/dreamdeck/Documents/code/3DReconstruction/frankmocap/detectors/hand_object_detector/lib/model/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c10lsERSoNS_12TensorTypeIdE
```

**Comment by MolianWH** [comment]
Also save video errors:
```shell
Unrecognized option 'x264opts'.
Error splitting the argument list: Option not found
```

Could you help me find the reasons? Thanks.

**Comment by penincillin** [comment]
@MolianWH 
This is a bug that has been fixed. Would you mind pull the latest code and try your demo again ?
Feel free to let me know if there's any other issues.

**Comment by MolianWH** [comment]
Sorry to replay late. And thanks. It works.
