### ISSUE TITLE
FrankmocapColabV2 - allow user to upload and download from google drive. with GUI

### ISSUE THREAD

**Issue by CGMikeG** [facebookresearch/frankmocap#166]
Hi All,

Please see below link to FrankmocapColabV2. Feel free to do with it as you want.

I've added a simple GUI to help users to upload and download directly from google drive.

https://colab.research.google.com/drive/15LTkHCC79VdyBAsmrJmuLBlyUa1jLo_P?usp=sharing

Hopefully, this will help people with old gpu or no gpu at all. :D

**Comment by penincillin** [comment]
@CGMikeG 
That's a great help! Thanks!

**Comment by UtsaChattopadhyay** [comment]
Hi all. Thanks for the colab implementation btw. It was a great help. So I have used it with multiple video inputs and some different arguments also, but it seems the final output video has some jitters in it. Same reflected in the pkl file as well when I made animation. Any idea how to get rid of the jitter or am I missing something? Thanks

**Comment by penincillin** [comment]
@UtsaChattopadhyay 
As FrankMocap is an image-based method, it is hard to avoid jitters. To resolve this issue, you can either average the predictions of adjacent frames or try video-based methods such as [VIBE](https://github.com/mkocabas/VIBE).

**Comment by kholoud707** [comment]
@CGMikeG  it help me thank you but it's only run demo_bodymocap I want to run as demo_frankmocap do you know how I can run it? it give me this message as an error:

 Loading Body Pose Estimator
Loading Third View Hand Detector
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/frankmocap/demo/demo_frankmocap.py", line 247, in <module>
    main()
  File "/content/frankmocap/demo/demo_frankmocap.py", line 230, in main
    hand_bbox_detector =  HandBboxDetector('third_view', device)
  File "/content/frankmocap/handmocap/hand_bbox_detector.py", line 311, in __init__
    self.model = Third_View_Detector()
  File "/content/frankmocap/handmocap/hand_bbox_detector.py", line 48, in __init__
    self.__load_hand_detector()
  File "/content/frankmocap/handmocap/hand_bbox_detector.py", line 57, in __load_hand_detector
    self.hand_detector = DefaultPredictor(cfg)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/defaults.py", line 222, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/usr/local/lib/python3.7/dist-packages/fvcore/common/checkpoint.py", line 141, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint extra_data/hand_module/hand_detector/model_0529999.pth not found!

**Comment by UtsaChattopadhyay** [comment]
I'm also facing the same error. Seems like the checkpoint is not downloaded in that folder. Any help is appreciated 👍

**Comment by UtsaChattopadhyay** [comment]
> @CGMikeG it help me thank you but it's only run demo_bodymocap I want to run as demo_frankmocap do you know how I can run it? it give me this message as an error:
> 
> Loading Body Pose Estimator Loading Third View Hand Detector Traceback (most recent call last): File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/usr/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/content/frankmocap/demo/demo_frankmocap.py", line 247, in main() File "/content/frankmocap/demo/demo_frankmocap.py", line 230, in main hand_bbox_detector = HandBboxDetector('third_view', device) File "/content/frankmocap/handmocap/hand_bbox_detector.py", line 311, in **init** self.model = Third_View_Detector() File "/content/frankmocap/handmocap/hand_bbox_detector.py", line 48, in **init** self.__load_hand_detector() File "/content/frankmocap/handmocap/hand_bbox_detector.py", line 57, in __load_hand_detector self.hand_detector = DefaultPredictor(cfg) File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/defaults.py", line 222, in **init** checkpointer.load(cfg.MODEL.WEIGHTS) File "/usr/local/lib/python3.7/dist-packages/fvcore/common/checkpoint.py", line 141, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint extra_data/hand_module/hand_detector/model_0529999.pth not found!

Hey @kholoud707 .. SO u can download it from these two links
'https://drive.google.com/uc?id=1H2tWsZkS7tDF8q1-jdjx6V9XrK25EDbE'
'https://drive.google.com/uc?id=1OqgexNM52uxsPG3i8GuodDOJAGFsYkPg'
and upload it to yr drive. larenatively use !gdown and download it in the specif folder to run it.
Hopefully this helps.

**Comment by shidaimingwang** [comment]
hi,i get some trouble      OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
