### ISSUE TITLE
demo for image folder

### ISSUE THREAD

**Issue by littlejiumi** [facebookresearch/frankmocap#184]
Traceback (most recent call last):
  File "/root/anaconda3/envs/zxh/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/zxh/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/cloud/group-body/xhzhang/CODES/frankmocap/demo/demo_bodymocap.py", line 178, in <module>
    main()
  File "/root/cloud/group-body/xhzhang/CODES/frankmocap/demo/demo_bodymocap.py", line 174, in main
    run_body_mocap(args, body_bbox_detector, body_mocap, visualizer)
  File "/root/cloud/group-body/xhzhang/CODES/frankmocap/demo/demo_bodymocap.py", line 120, in run_body_mocap
    res_img = visualizer.visualize(
  File "/root/cloud/group-body/xhzhang/CODES/frankmocap/renderer/visualizer.py", line 115, in visualize
    res_img = np.concatenate((res_img, rend_img), axis=1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1440 and the array at index 1 has size 1080
Segmentation fault (core dumped)

**Comment by penincillin** [comment]
@littlejiumi 
I don't quite understand your bug. Would you mind provide more information including the command you use, what kind of data you are processing, etc.
