### ISSUE TITLE
why did i run the install_pose2d.sh and still get this error?

### ISSUE THREAD

**Issue by szh-1598** [facebookresearch/frankmocap#193]
Traceback (most recent call last):
  File "/home/zhsy-zgh/下载/frankmocap-main/demo/demo_bodymocap.py", line 17, in <module>
    from bodymocap.body_bbox_detector import BodyPoseEstimator
  File "/home/zhsy-zgh/下载/frankmocap-main/bodymocap/body_bbox_detector.py", line 18, in <module>
    from detectors.body_pose_estimator.pose2d_models.with_mobilenet import PoseEstimationWithMobileNet
ModuleNotFoundError: No module named 'detectors'

**Comment by penincillin** [comment]
@szh-1598 
It seems like a path error. Under which directory you run this code?
