### ISSUE TITLE
Segmentation fault when saving the output as pkl for a single person 

### ISSUE THREAD

**Issue by mh-mahmoud** [facebookresearch/frankmocap#22]
Sometimes, when I save the output as pkl file with a --single _person argument, I got this error.

Traceback (most recent call last):
  File "/.conda/envs/venv_frankmocap/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/.conda/envs/venv_frankmocap/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./frankmocap/demo/demo_bodymocap.py", line 185, in <module>
    main()
  File "./frankmocap/demo/demo_bodymocap.py", line 181, in main
    run_body_mocap(args, body_bbox_detector, body_mocap, visualizer)
  File "./frankmocap/demo/demo_bodymocap.py", line 143, in run_body_mocap
    args, demo_type, image_path, body_bbox_list, hand_bbox_list, pred_output_list)
  File "./frankmocap/mocap_utils/demo_utils.py", line 236, in save_pred_to_pkl
    assert len(hand_bbox_list) == len(body_bbox_list)
AssertionError
Segmentation fault (core dumped)
%

**Comment by penincillin** [comment]
@mh-mahmoud 
Would you mind share the images that trigger this error ? And your options to run the demo.
Thanks !
