### ISSUE TITLE
No module named 'detectors'

### ISSUE THREAD

**Issue by spiderman82** [facebookresearch/frankmocap#37]
Traceback (most recent call last):
  File "/home/spider/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/spider/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/spider/frankmocap-master/demo/demo_frankmocap.py", line 23, in <module>
    from bodymocap.body_bbox_detector import BodyPoseEstimator
  File "/home/spider/frankmocap-master/bodymocap/body_bbox_detector.py", line 18, in <module>
    from detectors.body_pose_estimator.pose2d_models.with_mobilenet import PoseEstimationWithMobileNet
ModuleNotFoundError: No module named 'detectors'

**Comment by jhugestar** [comment]
Please make sure you have installed the required 2D pose detector. 

Essentially, you should have the following file as shown in the error log:

./detectors/body_pose_estimator/pose2d_models/with_mobilenet.py

**Comment by spiderman82** [comment]
Please tell me how i can install the "2D pose detector"?

**Comment by penincillin** [comment]
You can try to run https://github.com/facebookresearch/frankmocap/blob/master/scripts/install_pose2d.sh
