### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by Veyron2121** [facebookresearch/frankmocap#40]
Hello,

I am trying to run the egocentric hand pose estimation demo, and I followed the installation instructions in INSTALL.md accordingly. 

## Problem

However, when I run the command:
``` xvfb-run -a python -m demo.demo_handmocap --input_path ./sample_data/han_hand_short.mp4 --out_dir ./mocap_output --view_type ego_centric```

It successfully loads the Body Pose Estimator and the Ego Centric Hand Detector, but then provides the following error:
```
Traceback (most recent call last):
  File "/h/varunl/miniconda3/envs/frankmocap/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/h/varunl/miniconda3/envs/frankmocap/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scratch/ssd002/home/varunl/pair/HOPE/frankmocap/demo/demo_handmocap.py", line 178, in <module>
    main()
  File "/scratch/ssd002/home/varunl/pair/HOPE/frankmocap/demo/demo_handmocap.py", line 174, in main
    run_hand_mocap(args, bbox_detector, hand_mocap, visualizer)
  File "/scratch/ssd002/home/varunl/pair/HOPE/frankmocap/demo/demo_handmocap.py", line 100, in run_hand_mocap
    detect_output = bbox_detector.detect_hand_bbox(img_original_bgr.copy())
  File "/scratch/ssd002/home/varunl/pair/HOPE/frankmocap/handmocap/hand_bbox_detector.py", line 335, in detect_hand_bbox
    output = self.model.detect_hand_bbox(img_bgr)
  File "/scratch/ssd002/home/varunl/pair/HOPE/frankmocap/handmocap/hand_bbox_detector.py", line 283, in detect_hand_bbox
    bboxes, hand_types = self.__get_raw_hand_bbox(img)
  File "/scratch/ssd002/home/varunl/pair/HOPE/frankmocap/handmocap/hand_bbox_detector.py", line 223, in __get_raw_hand_bbox
    rois_label, loss_list = self.hand_detector(im_data, im_info, gt_boxes, num_boxes, box_info) 
  File "/h/varunl/miniconda3/envs/frankmocap/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch/ssd002/home/varunl/pair/HOPE/frankmocap/detectors/hand_object_detector/lib/model/faster_rcnn/faster_rcnn.py", line 57, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/h/varunl/miniconda3/envs/frankmocap/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch/ssd002/home/varunl/pair/HOPE/frankmocap/detectors/hand_object_detector/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/h/varunl/miniconda3/envs/frankmocap/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch/ssd002/home/varunl/pair/HOPE/frankmocap/detectors/hand_object_detector/lib/model/rpn/proposal_layer.py", line 147, in forward
    keep_idx_i = nms(proposals_single, scores_single.squeeze(1), nms_thresh)
RuntimeError: Not compiled with GPU support
Segmentation fault
```

## Attempted Solution

Now, when I tried looking it up, it appeared to be an issue with detectron2. The official solution seems to be just running the following command: ```python -c 'import torch; from torch.utils.cpp_extension import CUDA_HOME; print(torch.cuda.is_available(), CUDA_HOME)'``` to ensure that one has the correct CUDA version installed. The command tells me that I'm using CUDA-10.1, and that is also the corresponding detectron2 version I installed through INSTALL.md.

I'm unsure on how to proceed, and would greatly appreciate any support.

**Comment by Veyron2121** [comment]
I apologize - this seemed do have worked after re-installing all dependencies, for some reason. I'm sorry for the inconvenience.

**Comment by Arpitrf** [comment]
I am facing this exact issue. I am able to run non-egocentric case but facing issues with egocentric view_type. Following are my package versions:
![Screen Shot 2023-09-29 at 10 19 40 PM](https://github.com/facebookresearch/frankmocap/assets/14124093/f4801c4b-df29-439d-8eba-c5560588dfe3)

Any help would be appreciated!
