### ISSUE TITLE
opendr installation error during requirements.txt installation

### ISSUE THREAD

**Issue by Andrej730** [facebookresearch/frankmocap#43]
I get the following error during `pip install -r docs/requirements.txt`

```
Collecting opendr
  Using cached opendr-0.78.tar.gz (581 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/andrej/anaconda3/envs/venv_frankmocap/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ulk71kae/opendr_8f2944bcccaf44b7a6ea0938d5f0616f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ulk71kae/opendr_8f2944bcccaf44b7a6ea0938d5f0616f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ef5_e53v
         cwd: /tmp/pip-install-ulk71kae/opendr_8f2944bcccaf44b7a6ea0938d5f0616f/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ulk71kae/opendr_8f2944bcccaf44b7a6ea0938d5f0616f/setup.py", line 9, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
Guess the solution would be to make pip install numpy before trying to install opendr.

**Comment by penincillin** [comment]
Thanks for your kind reminding !

**Comment by archonic** [comment]
I just hit this myself. `pip install numpy` fixed it but shouldn't it be added to requirements.txt?
