### ISSUE TITLE
integration / copy_and_paste.py with smpl instead of smplx

### ISSUE THREAD

**Issue by Dayire** [facebookresearch/frankmocap#80]
Hello!

Thank you for your work, greatly helpful.

I'm having amazing results with the SMPL model (instead of the SMPLX) and I wanted to have a whole_body integration by copy paste using SMPL instead of SMPLX. I may be wrong but it seems to me that copy_and_paste.py was written only to integrate SMPLX parameters with the hand. 

in demo_frankmocap.py I forced args.use_smplx to False (as well as the function for Bodymocap call) but when debugging, it breaks:
`Traceback (most recent call last):
  File "/miniconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/miniconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/src/frankmocap/demo/demo_frankmocap.py", line 247, in <module>
    main()
  File "/src/frankmocap/demo/demo_frankmocap.py", line 243, in main
    run_frank_mocap(args, hand_bbox_detector, body_mocap, hand_mocap, visualizer)
  File "/src/frankmocap/demo/demo_frankmocap.py", line 179, in run_frank_mocap
    body_mocap, hand_mocap)
  File "/src/frankmocap/demo/demo_frankmocap.py", line 105, in run_regress
    pred_body_list, pred_hand_list, body_mocap.smpl, img_original_bgr.shape)
  File "/src/frankmocap/integration/copy_and_paste.py", line 97, in integration_copy_paste
    integral_output_list = list()
  File "/src/frankmocap/integration/copy_and_paste.py", line 97, in integration_copy_paste
    integral_output_list = list()
  File "/miniconda3/envs/py37/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/miniconda3/envs/py37/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
`
is there a way to use SMPL model instead of SMPLX in your integration copy_and_paste (without too much struggle?)

Thanks!

**Comment by penincillin** [comment]
Yes, integration module aims at connecting hands and bodies, while SMPL only support body. Therefore, SMPL-X is used in integration module.
