### ISSUE TITLE
error while running demo on google colab

### ISSUE THREAD

**Issue by magrenimish** [facebookresearch/frankmocap#85]
Hey Thanks a lot for providing a demo version! I'm trying to run the demo on google colab and face the following error when I run the demo:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/frankmocap/demo/demo_handmocap.py", line 16, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/content/frankmocap/handmocap/hand_bbox_detector.py", line 33, in <module>
    from detectors.hand_object_detector.lib.model.roi_layers import nms # might raise segmentation fault at the end of program
  File "/content/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/content/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: /content/frankmocap/detectors/hand_object_detector/lib/model/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa
Could you help me with this please!
cheers

**Comment by Singh47252** [comment]
How did you solved this error?

**Comment by magrenimish** [comment]
Its been a while so I don't remember the exact solution but I've managed to get it running. https://colab.research.google.com/drive/15DzL4T_jdEz2qXgcLZoDfl5-eLqOX82n?usp=sharing
