### ISSUE TITLE
Unable to run webcam demo

### ISSUE THREAD

**Issue by archonic** [facebookresearch/frankmocap#92]
I'm getting the following error when trying to run body mocap with the webcam input:

```
Traceback (most recent call last):
  File "/home/archonic/anaconda3/envs/venv_frankmocap/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/archonic/anaconda3/envs/venv_frankmocap/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/archonic/Code/frankmocap/demo/demo_bodymocap.py", line 179, in <module>
    main()
  File "/home/archonic/Code/frankmocap/demo/demo_bodymocap.py", line 175, in main
    run_body_mocap(args, body_bbox_detector, body_mocap, visualizer)
  File "/home/archonic/Code/frankmocap/demo/demo_bodymocap.py", line 76, in run_body_mocap
    image_path = osp.join(args.out_dir, "frames", f"scene_{cur_frame:05d}.jpg")
  File "/home/archonic/Code/frankmocap/demo/demo_bodymocap.py", line 76, in run_body_mocap
    image_path = osp.join(args.out_dir, "frames", f"scene_{cur_frame:05d}.jpg")
  File "/home/archonic/anaconda3/envs/venv_frankmocap/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/archonic/anaconda3/envs/venv_frankmocap/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```

L76 in demo_bodymocap.py is `image_path = osp.join(args.out_dir, "frames", f"scene_{cur_frame:05d}.jpg")`.

It looks like `args.out_dir` is `None` instead of `'./mocap_output'`.

**Comment by archonic** [comment]
I realized this is just a docs issue. `python -m demo.demo_bodymocap --input_path webcam --out_dir ./mocap_output` worked. I'll submit a PR to the docs that mention the webcam demo but don't provide the `out_dir`.

**Comment by penincillin** [comment]
@archonic 
Thanks for your contribution ! Looking forward to your PR.
