### ISSUE TITLE
Detectron undefined symbol running on Google colab

### ISSUE THREAD

**Issue by llxxll12345** [facebookresearch/frankmocap#94]
I'm trying to run the model on colab. I followed the install instructions but got the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/frankmocap/frankmocap/frankmocap/frankmocap/demo/demo_frankmocap.py", line 24, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/content/frankmocap/frankmocap/frankmocap/frankmocap/handmocap/hand_bbox_detector.py", line 19, in <module>
    from detectron2.engine import DefaultPredictor
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/__init__.py", line 11, in <module>
    from .hooks import *
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/hooks.py", line 18, in <module>
    from detectron2.evaluation.testing import flatten_results_dict
  File "/usr/local/lib/python3.7/dist-packages/detectron2/evaluation/__init__.py", line 2, in <module>
    from .cityscapes_evaluation import CityscapesInstanceEvaluator, CityscapesSemSegEvaluator
  File "/usr/local/lib/python3.7/dist-packages/detectron2/evaluation/cityscapes_evaluation.py", line 11, in <module>
    from detectron2.data import MetadataCatalog
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/usr/local/lib/python3.7/dist-packages/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, polygons_to_bitmask
  File "/usr/local/lib/python3.7/dist-packages/detectron2/structures/masks.py", line 9, in <module>
    from detectron2.layers.roi_align import ROIAlign
  File "/usr/local/lib/python3.7/dist-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/usr/local/lib/python3.7/dist-packages/detectron2/layers/deform_conv.py", line 11, in <module>
    from detectron2 import _C
ImportError: /usr/local/lib/python3.7/dist-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
```
What could be the cause for this error message?

**Comment by penincillin** [comment]
@llxxll12345 
This error seems to be caused by unsuccessful installation of detectron2. Would you mind try to solely install detectron-2 on colab ?
