### ISSUE TITLE
ImportError: /home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

### ISSUE THREAD

**Issue by monacv** [facebookresearch/frankmocap#96]
Do you know what is the reason for this error and how it can be resolved?
```

(frank) mona@goku:~/research/code/frankmocap$ python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mona/research/code/frankmocap/demo/demo_frankmocap.py", line 25, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/home/mona/research/code/frankmocap/handmocap/hand_bbox_detector.py", line 33, in <module>
    from detectors.hand_object_detector.lib.model.roi_layers import nms # might raise segmentation fault at the end of program
  File "/home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: /home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
```

env:

```
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.8.1+cu111'
>>> import detectron2
>>> detectron2.__version__
'0.4'
>>> from detectron2 import _C

```

Also,
```
$ python -m detectron2.utils.collect_env
----------------------  --------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
numpy                   1.19.5
detectron2              0.4 @/home/mona/venv/frank/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 11.1
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5, 8.0, 8.6
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1+cu111 @/home/mona/venv/frank/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 1650 Ti with Max-Q Design (arch=7.5)
CUDA_HOME               /usr
Pillow                  8.1.0
torchvision             0.9.1+cu111 @/home/mona/venv/frank/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.3.post20210311
cv2                     4.5.1
----------------------  --------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 


```

**Comment by monacv** [comment]
I uninstalled Detectron2, and installed it again following the README instruction and still get the same error:

```
(frank) mona@goku:~/research/code/frankmocap$ pip uninstall detectron2
Found existing installation: detectron2 0.4+cu111
Uninstalling detectron2-0.4+cu111:
  Would remove:
    /home/mona/venv/frank/lib/python3.8/site-packages/detectron2-0.4+cu111.dist-info/*
    /home/mona/venv/frank/lib/python3.8/site-packages/detectron2/*
Proceed (y/n)? y
  Successfully uninstalled detectron2-0.4+cu111
(frank) mona@goku:~/research/code/frankmocap$ python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-6hero4cq
  Running command git clone -q https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-6hero4cq
Requirement already satisfied: Pillow>=7.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (8.1.0)
Requirement already satisfied: cloudpickle in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (1.6.0)
Requirement already satisfied: future in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (0.18.2)
Collecting fvcore<0.1.6,>=0.1.5
  Using cached fvcore-0.1.5.post20210415.tar.gz (48 kB)
Collecting iopath<0.1.8,>=0.1.7
  Using cached iopath-0.1.7-py3-none-any.whl (19 kB)
Requirement already satisfied: matplotlib in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (3.3.3)
Collecting omegaconf==2.1.0.dev22
  Using cached omegaconf-2.1.0.dev22-py3-none-any.whl (66 kB)
Requirement already satisfied: pycocotools>=2.0.2 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (2.0.2)
Requirement already satisfied: pydot in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (1.4.1)
Requirement already satisfied: tabulate in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (0.8.7)
Requirement already satisfied: tensorboard in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (2.4.1)
Requirement already satisfied: termcolor>=1.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (1.1.0)
Requirement already satisfied: tqdm>4.29.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (4.56.0)
Requirement already satisfied: yacs>=0.1.6 in /home/mona/venv/frank/lib/python3.8/site-packages (from detectron2==0.4) (0.1.8)
Requirement already satisfied: numpy in /home/mona/venv/frank/lib/python3.8/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.4) (1.19.5)
Requirement already satisfied: pyyaml>=5.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.4) (5.3.1)
Requirement already satisfied: portalocker in /home/mona/venv/frank/lib/python3.8/site-packages (from iopath<0.1.8,>=0.1.7->detectron2==0.4) (2.0.0)
Requirement already satisfied: cycler>=0.10 in /home/mona/venv/frank/lib/python3.8/site-packages (from matplotlib->detectron2==0.4) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from matplotlib->detectron2==0.4) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from matplotlib->detectron2==0.4) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/mona/venv/frank/lib/python3.8/site-packages (from matplotlib->detectron2==0.4) (2.4.7)
Collecting antlr4-python3-runtime==4.8
  Using cached antlr4-python3-runtime-4.8.tar.gz (112 kB)
Requirement already satisfied: cython>=0.27.3 in /home/mona/venv/frank/lib/python3.8/site-packages (from pycocotools>=2.0.2->detectron2==0.4) (0.29.21)
Requirement already satisfied: setuptools>=18.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from pycocotools>=2.0.2->detectron2==0.4) (44.0.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.24.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.7.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (0.36.2)
Requirement already satisfied: absl-py>=0.4 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (0.11.0)
Requirement already satisfied: six>=1.10.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.15.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (0.4.2)
Requirement already satisfied: grpcio>=1.24.3 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (2.25.1)
Requirement already satisfied: werkzeug>=0.11.15 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (3.3.3)
Requirement already satisfied: protobuf>=3.6.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from tensorboard->detectron2==0.4) (3.14.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in /home/mona/venv/frank/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (4.7)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (4.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.4) (1.3.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.4) (1.26.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/mona/venv/frank/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2==0.4) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.4) (3.1.0)
Building wheels for collected packages: detectron2, fvcore, antlr4-python3-runtime
  Building wheel for detectron2 (setup.py) ... done
  Created wheel for detectron2: filename=detectron2-0.4-cp38-cp38-linux_x86_64.whl size=6323671 sha256=917b8b3129b6dcd9d08adcfe416a1642b1098bf55bb558459a3a05d980526016
  Stored in directory: /tmp/pip-ephem-wheel-cache-qzirlv_s/wheels/19/ac/65/e48e5e4ec2702274d927c5a6efb75709b24014371d3bb778f2
  Building wheel for fvcore (setup.py) ... done
  Created wheel for fvcore: filename=fvcore-0.1.5.post20210415-py3-none-any.whl size=59309 sha256=db8695b22ae60461ff8dfc7784e246666c2fc5b5d4904ab045878705d2f93753
  Stored in directory: /home/mona/.cache/pip/wheels/fc/05/a0/ba4b3385c0294621f870e0b3762ebf2da773407544d2b41212
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141230 sha256=f11b31d25f85f2303391f69b71a20c7f14bec0d07f7d6fdb849c6e51ed716e61
  Stored in directory: /home/mona/.cache/pip/wheels/c8/d0/ab/d43c02eaddc5b9004db86950802442ad9a26f279c619e28da0
Successfully built detectron2 fvcore antlr4-python3-runtime
Installing collected packages: iopath, fvcore, antlr4-python3-runtime, omegaconf, detectron2
  Attempting uninstall: iopath
    Found existing installation: iopath 0.1.2
    Uninstalling iopath-0.1.2:
      Successfully uninstalled iopath-0.1.2
  Attempting uninstall: fvcore
    Found existing installation: fvcore 0.1.3.post20210311
    Uninstalling fvcore-0.1.3.post20210311:
      Successfully uninstalled fvcore-0.1.3.post20210311
  Attempting uninstall: omegaconf
    Found existing installation: omegaconf 2.0.6
    Uninstalling omegaconf-2.0.6:
      Successfully uninstalled omegaconf-2.0.6
Successfully installed antlr4-python3-runtime-4.8 detectron2-0.4 fvcore-0.1.5.post20210415 iopath-0.1.7 omegaconf-2.1.0.dev22
(frank) mona@goku:~/research/code/frankmocap$ python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mona/research/code/frankmocap/demo/demo_frankmocap.py", line 25, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/home/mona/research/code/frankmocap/handmocap/hand_bbox_detector.py", line 33, in <module>
    from detectors.hand_object_detector.lib.model.roi_layers import nms # might raise segmentation fault at the end of program
  File "/home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: /home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
(frank) mona@goku:~/research/code/frankmocap$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import detectron2
>>> detectron2.__version__
'0.4'

```

**Comment by penincillin** [comment]
@monacv 
Would you mind try to check if you have successfully installed the hand detectors ?
You can follow the commands in this [installation guidance](https://github.com/facebookresearch/frankmocap/blob/master/scripts/install_hand_detectors.sh) step-by-step.

**Comment by monacv** [comment]
@penincillin thanks a lot for your reply. Please let me know if you might be able to guide me. Thanks a lot for your time.

I followed the installation of the hand detector (I am not sure if it fully went through since I got a few "FAIL" items) and then ran the original command again and still same error:

```
(frank) mona@goku:~/research/code/frankmocap$ ./scripts/install_hand_detectors.sh 
Requirement already satisfied: gdown in /home/mona/venv/frank/lib/python3.8/site-packages (3.12.2)
Requirement already satisfied: tqdm in /home/mona/venv/frank/lib/python3.8/site-packages (from gdown) (4.56.0)
Requirement already satisfied: requests[socks] in /home/mona/venv/frank/lib/python3.8/site-packages (from gdown) (2.25.1)
Requirement already satisfied: filelock in /home/mona/venv/frank/lib/python3.8/site-packages (from gdown) (3.0.12)
Requirement already satisfied: six in /home/mona/venv/frank/lib/python3.8/site-packages (from gdown) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests[socks]->gdown) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests[socks]->gdown) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests[socks]->gdown) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/mona/venv/frank/lib/python3.8/site-packages (from requests[socks]->gdown) (1.26.2)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in /home/mona/venv/frank/lib/python3.8/site-packages (from requests[socks]->gdown) (1.7.1)
fatal: destination path 'hand_object_detector' already exists and is not an empty directory.
running build
running build_py
running build_ext
/home/mona/venv/frank/lib/python3.8/site-packages/torch/utils/cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
running develop
running egg_info
writing faster_rcnn.egg-info/PKG-INFO
writing dependency_links to faster_rcnn.egg-info/dependency_links.txt
writing top-level names to faster_rcnn.egg-info/top_level.txt
reading manifest file 'faster_rcnn.egg-info/SOURCES.txt'
writing manifest file 'faster_rcnn.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.8/model/_C.cpython-38-x86_64-linux-gnu.so -> model
Creating /home/mona/venv/frank/lib/python3.8/site-packages/faster-rcnn.egg-link (link to .)
faster-rcnn 0.1 is already the active version in easy-install.pth

Installed /home/mona/research/code/frankmocap/detectors/hand_object_detector/lib
Processing dependencies for faster-rcnn==0.1
Finished processing dependencies for faster-rcnn==0.1
Cloning into 'hand_detector.d2'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 28 (delta 13), reused 20 (delta 8), pack-reused 0
Receiving objects: 100% (28/28), 763.74 KiB | 4.49 MiB/s, done.
Resolving deltas: 100% (13/13), done.
mv: cannot move 'hand_detector.d2' to 'hand_only_detector/hand_detector.d2': Directory not empty
Downloading...
From: https://drive.google.com/uc?id=1H2tWsZkS7tDF8q1-jdjx6V9XrK25EDbE
To: /home/mona/research/code/frankmocap/detectors/faster_rcnn_1_8_132028.pth
378MB [01:02, 6.08MB/s] 
Downloading...
From: https://drive.google.com/uc?id=1OqgexNM52uxsPG3i8GuodDOJAGFsYkPg
To: /home/mona/research/code/frankmocap/detectors/model_0529999.pth
838MB [02:09, 6.48MB/s] 
(frank) mona@goku:~/research/code/frankmocap$ python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mona/research/code/frankmocap/demo/demo_frankmocap.py", line 25, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/home/mona/research/code/frankmocap/handmocap/hand_bbox_detector.py", line 33, in <module>
    from detectors.hand_object_detector.lib.model.roi_layers import nms # might raise segmentation fault at the end of program
  File "/home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: /home/mona/research/code/frankmocap/detectors/hand_object_detector/lib/model/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

```

**Comment by monacv** [comment]
update. I didn't run the script using ./ but following it step by step and it worked. Thanks a lot. :)

**Comment by kodapurath** [comment]
> update. I didn't run the script using ./ but following it step by step and it worked. Thanks a lot. :)

Could you please elaborate, I am facing a similar issue of 'undefined symbol'

**Comment by mmxgn** [comment]
Hi, 

The solutions presented here didn't work for me. What worked though was first running:

`conda install -c conda-forge cxx-compiler` before running `bash ./scripts/install_hand_detectors.sh`

**Comment by Lruidong** [comment]
> 你好，
> 
> 这里介绍的解决方案对我不起作用。但首先运行的是：
> 
> `conda install -c conda-forge cxx-compiler` 跑步前 `bash ./scripts/install_hand_detectors.sh`

can you run ?now .  I face the same problem

**Comment by Lruidong** [comment]
> > 更新。我没有使用 ./ 运行脚本，而是一步一步地跟随它并且它起作用了。非常感谢。:)
> 
> 能否请您详细说明一下，我面临着类似的“未定义符号”问题

 excuse me .Have you solved it now?

**Comment by relh** [comment]
> > update. I didn't run the script using ./ but following it step by step and it worked. Thanks a lot. :)
> 
> Could you please elaborate, I am facing a similar issue of 'undefined symbol'

This probably means that Mona ran each command one at a time in her terminal rather than all at once.
