### ISSUE TITLE
  File "./frankmocap/bodymocap/body_bbox_detector.py", line 18, in <module>     from detectors.body_pose_estimator.pose2d_models.with_mobilenet import PoseEstimationWithMobileNet   File "./frankmocap/detectors/body_pose_estimator/pose2d_models/with_mobilenet.py", line 4, in <module>     from modules.conv import conv, conv_dw, conv_dw_no_bn ModuleNotFoundError: No module named 'modules'

### ISSUE THREAD

**Issue by monacv** [facebookresearch/frankmocap#97]
When I am trying to use your code modules in my own test demo, I get this error (despite getting no error in frank mocap demo python file):

```
$ python demo.py 
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    from bodymocap.body_bbox_detector import BodyPoseEstimator
  File "./frankmocap/bodymocap/body_bbox_detector.py", line 18, in <module>
    from detectors.body_pose_estimator.pose2d_models.with_mobilenet import PoseEstimationWithMobileNet
  File "./frankmocap/detectors/body_pose_estimator/pose2d_models/with_mobilenet.py", line 4, in <module>
    from modules.conv import conv, conv_dw, conv_dw_no_bn
ModuleNotFoundError: No module named 'modules'
```
I am not sure how to fix this.

**Comment by penincillin** [comment]
@monacv 
First, please check you have installed detectron2 successfully.
Second, after installing detectron2, please try to install the [hand_object detector](https://github.com/ddshan/hand_object_detector) and [hand_detector](https://github.com/ddshan/hand_detector.d2) step-by-step.

**Comment by monacv** [comment]
@penincillin I have followed the instruction in https://github.com/facebookresearch/frankmocap/blob/master/scripts/install_hand_detectors.sh step-by-step and have installed them. Am I wrong? I am able to run the demo/demo_frankmocap.py with no problem. Could you help me how to debug this please? thank you

**Comment by monacv** [comment]
Here's the code:

```
import cv2
import matplotlib.pyplot as plt
import numpy as np
import tqdm
import torch
from PIL import Image

import neural_renderer as nr
from detectron2.data import MetadataCatalog
from detectron2.structures import Boxes, BitMasks
from detectron2.utils.visualizer import Visualizer as PointRendVisualizer

from phosa.bodymocap import (
    get_bodymocap_predictor,
    process_mocap_predictions,
    visualize_orthographic,
)
from phosa.global_opt import optimize_human_object, visualize_human_object
from phosa.pointrend import get_pointrend_predictor
from phosa.pose_optimization import find_optimal_poses
from phosa.utils import bbox_xy_to_wh, center_vertices

prop = torch.cuda.get_device_properties(0)
print(f"GPU: {prop.name}")
print(f"VRAM: {prop.total_memory / 1e9:.1f}GB")
print(f"CC: {prop.major}.{prop.minor}")
```
Here's the error:

```
(phosa) mona@goku:~/research/code/phosa$ python test_frank.py 
Traceback (most recent call last):
  File "test_frank.py", line 13, in <module>
    from phosa.bodymocap import (
  File "/home/mona/research/code/phosa/phosa/bodymocap.py", line 12, in <module>
    from bodymocap.body_bbox_detector import BodyPoseEstimator
  File "./external/frankmocap/bodymocap/body_bbox_detector.py", line 18, in <module>
    from detectors.body_pose_estimator.pose2d_models.with_mobilenet import PoseEstimationWithMobileNet
  File "./external/frankmocap/detectors/body_pose_estimator/pose2d_models/with_mobilenet.py", line 4, in <module>
    from modules.conv import conv, conv_dw, conv_dw_no_bn
ModuleNotFoundError: No module named 'modules'

```

I have added these few lines to beginning of phosa/bodymocap.py:

```
# Copyright (c) Facebook, Inc. and its affiliates.
"""
Wrapper for Human Pose Estimator using BodyMocap.
See: https://github.com/facebookresearch/frankmocap
"""
import numpy as np
import torch

from bodymocap.body_mocap_api import BodyMocap
from handmocap.hand_mocap_api import HandMocap
#frank
from bodymocap.body_bbox_detector import BodyPoseEstimator
from handmocap.hand_bbox_detector import HandBboxDetector

from detectron2.structures.masks import BitMasks

from phosa.constants import BODY_MOCAP_REGRESSOR_CKPT, BODY_MOCAP_SMPL_PATH, HAND_MOCAP_REGRESSOR_CKPT, IMAGE_SIZE
from phosa.utils import OrthographicRenderer, bbox_xy_to_wh, local_to_global_cam

```

**Comment by penincillin** [comment]
Aha, it seems to be caused by the incorrect path.
Where do you run this code ? The recommend path is within the ``frankmocap/'' directory.

**Comment by monacv** [comment]
thanks a lot @penincillin  for your response. My test code is located in the following directory and I can't move it
```
(phosa) mona@goku:~/research/code/phosa$ vi test_frank.py 
(phosa) mona@goku:~/research/code/phosa$ pwd
/home/mona/research/code/phosa
```


**How can I change the imports so they'd work?**



```
(phosa) mona@goku:~/research/code/phosa$ python test_frank.py 
Traceback (most recent call last):
  File "test_frank.py", line 13, in <module>
    from phosa.bodymocap import (
  File "/home/mona/research/code/phosa/phosa/bodymocap.py", line 12, in <module>
    from bodymocap.body_bbox_detector import BodyPoseEstimator
  File "./external/frankmocap/bodymocap/body_bbox_detector.py", line 18, in <module>
    from detectors.body_pose_estimator.pose2d_models.with_mobilenet import PoseEstimationWithMobileNet
  File "./external/frankmocap/detectors/body_pose_estimator/pose2d_models/with_mobilenet.py", line 4, in <module>
    from modules.conv import conv, conv_dw, conv_dw_no_bn
ModuleNotFoundError: No module named 'modules'

```

Frank Mocap is located here:

```
(phosa) mona@goku:~/research/code/phosa$ ls external/frankmocap/
total 120K
-rwxrwxrwx  1 mona mona 4.5K Dec 23 18:46 README.md
-rwxrwxrwx  1 mona mona  21K Dec 23 18:46 LICENSE
-rwxrwxrwx  1 mona mona 1.3K Dec 23 18:46 CONTRIBUTING.md
-rwxrwxrwx  1 mona mona 3.3K Dec 23 18:46 CODE_OF_CONDUCT.md
-rwxrwxrwx  1 mona mona  907 Jan 20 03:05 requirements.txt
drwxrwxrwx  2 mona mona 4.0K Jan 29 01:24 output
-rwxrwxrwx  1 mona mona  457 Jan 29 01:28 .gitignore
drwxrwxrwx  5 mona mona 4.0K Feb 24 16:43 bodymocap
drwxrwxrwx  2 mona mona 4.0K Feb 24 16:43 docs
drwxrwxrwx  4 mona mona 4.0K Feb 24 16:43 handmocap
drwxrwxrwx  4 mona mona 4.0K Feb 24 16:43 renderer
drwxrwxrwx  2 mona mona 4.0K Feb 24 16:43 scripts
drwxrwxrwx  5 mona mona 4.0K Feb 24 16:44 extra_data
drwxrwxrwx  2 mona mona 4.0K Feb 24 16:44 sample_data
drwxrwxrwx  2 mona mona 4.0K Feb 24 16:44 input
drwxrwxrwx  3 mona mona 4.0K Feb 24 16:44 .idea
drwxrwxrwx  5 mona mona 4.0K Feb 24 16:44 ..
drwxrwxrwx  3 mona mona 4.0K Mar 15 23:20 mocap_utils
drwxrwxrwx  8 mona mona 4.0K Apr 15 19:06 .git
drwxrwxr-x  5 mona mona 4.0K Apr 17 04:14 detectors
drwxrwxr-x  4 mona mona 4.0K Apr 17 04:14 mocap_output
drwxrwxrwx 18 mona mona 4.0K Apr 17 04:14 .
drwxrwxrwx  3 mona mona 4.0K Apr 17 05:53 integration
drwxrwxrwx  3 mona mona 4.0K Apr 21 01:35 demo

```

**Comment by kovalepskaia** [comment]
My solution is that I enabled gpu card on my win 10.

**Comment by penincillin** [comment]
@monacv 
Would you mind show me the content in your ```phosa``` directory ?

**Comment by kovalepskaia** [comment]
> @monacv
> Would you mind show me the content in your `phosa/` directory and the content of `test_frank.py` ?

I install following the guide https://github.com/carlosedubarreto/frankmocap_win_install
Then, I do several steps:
i) git clone the source frankmocap in the folder frankmocap_win_install. 
ii) copy folder bodymocap (in the source frankmocap) to the folder frankmocap_win_install
