### ISSUE TITLE
ValueError 

### ISSUE THREAD

**Issue by usernamex1x23** [facebookresearch/frankmocap#98]
**command.**
  python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl

**error** 
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**full output from command prompt** 
(frankmocap) D:\video\ffmpeg\frankmocap-master>python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output
Traceback (most recent call last):
  File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Newfolder\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\video\ffmpeg\frankmocap-master\demo\demo_frankmocap.py", line 24, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "D:\video\ffmpeg\frankmocap-master\handmocap\hand_bbox_detector.py", line 19, in <module>
    from detectron2.engine import DefaultPredictor
  File "D:\Newfolder\envs\frankmocap\lib\site-packages\detectron2\engine\__init__.py", line 11, in <module>
    from .hooks import *
  File "D:\Newfolder\envs\frankmocap\lib\site-packages\detectron2\engine\hooks.py", line 17, in <module>
    from detectron2.evaluation.testing import flatten_results_dict
  File "D:\Newfolder\envs\frankmocap\lib\site-packages\detectron2\evaluation\__init__.py", line 2, in <module>
    from .cityscapes_evaluation import CityscapesInstanceEvaluator, CityscapesSemSegEvaluator
  File "D:\Newfolder\envs\frankmocap\lib\site-packages\detectron2\evaluation\cityscapes_evaluation.py", line 11, in <module>
    from detectron2.data import MetadataCatalog
  File "D:\Newfolder\envs\frankmocap\lib\site-packages\detectron2\data\__init__.py", line 4, in <module>
    from .build import (
  File "D:\Newfolder\envs\frankmocap\lib\site-packages\detectron2\data\build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "D:\Newfolder\envs\frankmocap\lib\site-packages\detectron2\structures\__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, rasterize_polygons_within_box, polygons_to_bitmask
  File "D:\Newfolder\envs\frankmocap\lib\site-packages\detectron2\structures\masks.py", line 6, in <module>
    import pycocotools.mask as mask_util
  File "D:\Newfolder\envs\frankmocap\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

(frankmocap) D:\video\ffmpeg\frankmocap-master>

**Comment by penincillin** [comment]
@usernamex1x23 
It seems that you run the code on a Windows computer / server. Officially, we only support linux (Ubuntu). Therefore, would you mind to try it on Ubuntu or at least Linux ?
